local_costmap:
  global_frame: turtlebot3_1/odom 
  robot_base_frame: turtlebot3_1/base_footprint
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5  

  static_map: false
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.05

  plugins:
    - {name: laser_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  laser_layer:
    observation_sources: scan
    scan:
      topic: scan                 # Usato in modo relativo: diventerà, ad esempio, /turtlebot3_1/scan se il nodo è namespaced
      sensor_frame: turtlebot3_1/base_scan       # Verifica che questo sia il frame pubblicato dal laser
      data_type: LaserScan
      expected_update_rate: 0.4
      marking: true
      clearing: true
